=== judegordon/hgps/schemas/data_index/data_index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/judegordon/hgps/main/schemas/data_index/data_index.json",
  "title": "Index file for input data",
  "description": "Metadata and paths for HealthGPS input files.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Optional JSON Schema identifier."
    },
    "country": {
      "$ref": "components/country.json"
    },
    "demographic": {
      "$ref": "components/demographic.json"
    },
    "diseases": {
      "$ref": "components/diseases.json"
    },
    "analysis": {
      "$ref": "components/analysis.json"
    }
  },
  "required": [
    "country",
    "demographic",
    "diseases",
    "analysis"
  ],
  "additionalProperties": false
}

=== judegordon/hgps/data/undb/index.json
{
    "$schema": "https://raw.githubusercontent.com/judegordon/hgps/main/schemas/data_index/data_index.json",
    "country": {
        "format": "csv",
        "delimiter": ",",
        "encoding": "UTF8",
        "description": "ISO 3166-1 country codes.",
        "source": "International Organization for Standardization",
        "url": "https://www.iso.org/iso-3166-country-codes.html",
        "license": "N/A",
        "path": "",
        "file_name": "countries.csv"
    },
    "demographic": {
        "format": "csv",
        "delimiter": ",",
        "encoding": "UTF8",
        "description": "United Nations (UN) population estimates and projections.",
        "source": "UN Database - World Population Prospects 2019",
        "url": "https://population.un.org/wpp/",
        "license": "Creative Commons license",
        "path": "",
        "age_limits": [0, 110],
        "time_limits": [1950, 2100],
        "projections": 2022,
        "population": {
            "description": "Total population by sex, annually from 1950 to 2100.",
            "path": "population",
            "file_name": "P{COUNTRY_CODE}.csv"
        },
        "mortality": {
            "description": "Number of deaths by sex, annually from 1950 to 2100.",
            "path": "mortality",
            "file_name": "M{COUNTRY_CODE}.csv"
        },
        "indicators": {
            "description": "Several demographic indicators by year, e.g. births, deaths and life expectancy.",
            "path": "indicators",
            "file_name": "Pi{COUNTRY_CODE}.csv"
        }
    },
    "diseases": {
        "format": "csv",
        "delimiter": ",",
        "encoding": "UTF8",
        "description": "Diseases indicators, measures and relative risk factors.",
        "source": "The Institute for Health Metrics and Evaluation - IHME",
        "url": "http://www.healthdata.org/",
        "license": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License",
        "path": "diseases",
        "age_limits": [1, 110],
        "time_year": 2019,
        "disease": {
            "path": "{DISEASE_TYPE}",
            "file_name": "D{COUNTRY_CODE}.csv",
            "relative_risk": {
                "path": "relative_risk",
                "to_disease": {
                    "path": "disease",
                    "file_name": "{DISEASE_TYPE}_{DISEASE_TYPE}.csv",
                    "default_value": 1.0
                },
                "to_risk_factor": {
                    "path": "risk_factor",
                    "file_name": "{GENDER}_{DISEASE_TYPE}_{RISK_FACTOR}.csv"
                }
            },
            "parameters": {
                "path": "P{COUNTRY_CODE}",
                "files": {
                    "distribution": "prevalence_distribution.csv",
                    "survival_rate": "survival_rate_parameters.csv",
                    "death_weight": "death_weights.csv"
                }
            }
        },
        "registry": [
            {
                "group": "other",
                "id": "alzheimer",
                "name": "Alzheimer"
            },
            {
                "group": "other",
                "id": "angina",
                "name": "Angina"
            },
            {
                "group": "other",
                "id": "anxiety",
                "name": "Anxiety Disorder"
            },
            {
                "group": "other",
                "id": "asthma",
                "name": "Asthma"
            },
            {
                "group": "other",
                "id": "dermatitis",
                "name": "Atopic Dermatitis"
            },
            {
                "group": "other",
                "id": "cataract",
                "name": "Blindness Due to Cataract Unsqueezed"
            },
            {
                "group": "other",
                "id": "pulmonar",
                "name": "Chronic Obstructive Pulmonary Disease"
            },
            {
                "group": "other",
                "id": "pancreatitis",
                "name": "Chronic Pancreatitis"
            },
            {
                "group": "other",
                "id": "cirrhosis",
                "name": "Cirrhosis"
            },
            {
                "group": "other",
                "id": "diabetes",
                "name": "Diabetes"
            },
            {
                "group": "other",
                "id": "gallbladder",
                "name": "Gallbladder and Biliary Diseases"
            },
            {
                "group": "other",
                "id": "reflux",
                "name": "Gastroesophageal Reflux Disease"
            },
            {
                "group": "other",
                "id": "gout",
                "name": "Gout"
            },
            {
                "group": "other",
                "id": "lowbackpain",
                "name": "Low Back Pain"
            },
            {
                "group": "other",
                "id": "depression",
                "name": "Major Depressive Disorder"
            },
            {
                "group": "other",
                "id": "migraine",
                "name": "Migraine"
            },
            {
                "group": "other",
                "id": "multiplesclerosis",
                "name": "Multiple Sclerosis"
            },
            {
                "group": "other",
                "id": "myocardial",
                "name": "Myocardial Infarction"
            },
            {
                "group": "other",
                "id": "osteoarthritiship",
                "name": "Osteoarthritis of the hip"
            },
            {
                "group": "other",
                "id": "osteoarthritisknee",
                "name": "Osteoarthritis Of The Knee"
            },
            {
                "group": "other",
                "id": "parkinson",
                "name": "Parkinson Disease"
            },
            {
                "group": "other",
                "id": "psoriasis",
                "name": "Psoriasis"
            },
            {
                "group": "other",
                "id": "arthritis",
                "name": "Rheumatoid Arthritis"
            },
            {
                "group": "other",
                "id": "visionimpairment",
                "name": "Vision Impairment Due to Cataract Unsqueezed"
            },
            {
                "group": "other",
                "id": "intracerebralhemorrhage",
                "name": "Intracerebral Hemorrhage"
            },
            {
                "group": "other",
                "id": "ischemicheartdisease",
                "name": "Ischemic Heart Disease"
            },
            {
                "group": "other",
                "id": "stroke",
                "name": "stroke"
            },
            {
                "group": "other",
                "id": "ischemicstroke",
                "name": "Ischemic Stroke"
            },
            {
                "group": "other",
                "id": "subarachnoidhemorrhage",
                "name": "Subarachnoid Hemorrhage"
            },
            {
                "group": "other",
                "id": "chronickidneydisease",
                "name": "Chronic kidney disease"
            },
            {
                "group": "cancer",
                "id": "breastcancer",
                "name": "Breast Cancer"
            },
            {
                "group": "cancer",
                "id": "colorectalcancer",
                "name": "Colorectum Cancer"
            },
            {
                "group": "cancer",
                "id": "trachealbronchuslungcancer",
                "name": "Tracheal, bronchus, and lung cancer"
            },
            {
                "group": "cancer",
                "id": "esophaguscancer",
                "name": "Esophagus Cancer"
            },
            {
                "group": "cancer",
                "id": "gallbladdercancer",
                "name": "Gallbladder Cancer"
            },
            {
                "group": "cancer",
                "id": "kidneycancer",
                "name": "Kidney Cancer"
            },
            {
                "group": "cancer",
                "id": "livercancer",
                "name": "Liver Cancer"
            },
            {
                "group": "cancer",
                "id": "ovarycancer",
                "name": "Ovary Cancer"
            },
            {
                "group": "cancer",
                "id": "pancreascancer",
                "name": "Pancreas Cancer"
            },
            {
                "group": "cancer",
                "id": "stomachcancer",
                "name": "Stomach Cancer"
            },
            {
                "group": "cancer",
                "id": "thyroidcancer",
                "name": "Thyroid Cancer"
            }
        ]
    },
    "analysis": {
        "format": "csv",
        "delimiter": ",",
        "encoding": "UTF8",
        "description": "Observed burden of disease measures and disability weights.",
        "source": "The Institute for Health Metrics and Evaluation - IHME",
        "url": "http://www.healthdata.org/",
        "license": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License",
        "path": "analysis",
        "age_limits": [1, 110],
        "time_year": 2019,
        "disability_file_name": "disability_weights.csv",
        "lms_file_name": "lms_parameters.csv",
        "cost_of_disease": {
            "path": "cost",
